FROM golang:1.16.7 AS builder


WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum

COPY code/ code/

COPY vendor/ vendor/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -mod=vendor -a -o server ./code/server.go

FROM alpine
WORKDIR /
COPY --from=builder /workspace/server .
COPY data/data.tf /data/data.tf
COPY data/rds     /data/rds
COPY bin/terraform /usr/bin/terraform
COPY bin/.terraform.d /root/.terraform.d
RUN echo http://mirrors.aliyun.com/alpine/v3.10/main/ > /etc/apk/repositories && \
    echo http://mirrors.aliyun.com/alpine/v3.10/community/ >> /etc/apk/repositories
RUN apk update && apk upgrade
RUN apk add --no-cache git

ENTRYPOINT ["/server"]
